# Generated by Django 4.1.13 on 2023-12-21 05:39

from django.db import migrations, models
import djongo.models.fields
import site1.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, max_length=100, primary_key=True, serialize=False)),
                ('str', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='default_username', max_length=150, unique=True)),
                ('first_name', models.CharField(default='fname', max_length=30)),
                ('last_name', models.CharField(default='lname', max_length=30)),
                ('email', models.EmailField(default='default@example.com', max_length=254, unique=True)),
                ('password', models.CharField(default='fname', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('quiz_easy', djongo.models.fields.ArrayField(model_container=site1.models.QuizAttempt)),
                ('quiz_medium', djongo.models.fields.ArrayField(model_container=site1.models.QuizAttempt)),
                ('quiz_hard', djongo.models.fields.ArrayField(model_container=site1.models.QuizAttempt)),
            ],
        ),
    ]
