# Generated by Django 4.1.13 on 2023-12-22 08:48

from django.db import migrations, models
import djongo.models.fields
import site1.models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, max_length=100, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('questions', djongo.models.fields.ArrayField(model_container=site1.models.Questions)),
                ('answers', djongo.models.fields.ArrayField(model_container=site1.models.Questions)),
            ],
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='id',
            new_name='_id',
        ),
    ]
