# Generated by Django 4.1.13 on 2023-12-23 10:44

from django.db import migrations, models
import djongo.models.fields
import site1.models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('questions', djongo.models.fields.ArrayField(model_container=site1.models.Questions)),
                ('answers', djongo.models.fields.ArrayField(model_container=site1.models.Questions)),
            ],
        ),
    ]
