# Generated by Django 4.1.13 on 2023-12-14 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0002_easy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Easy',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
