# Generated by Django 4.1.13 on 2023-12-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0002_quizattempt_rename_id_questions__id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
    ]
