# Generated by Django 4.1.13 on 2023-12-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0005_questions_userquiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquiz',
            name='user',
        ),
        migrations.AddField(
            model_name='userquiz',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
