# Generated by Django 4.1.13 on 2023-12-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0006_remove_userquiz_user_userquiz_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='default_username', max_length=100, primary_key=True, serialize=False),
        ),
    ]
